favicon: null
name: United Colors of HIV
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.217508
  brandStrength: 0
  lightness: 1
  brandColors:
    - '#8e8a87'
    - '#fbffff'
    - '#020808'
    - '#6a4d2f'
    - '#cac9c7'
  rhythmicContrast: 0
typography_spectrum: 0.40884
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
