name: United Colors of HIV
favicon: null
layout_spectrum: 1
typography_spectrum: 0.40884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#93b6e0'
    - '#176f49'
    - '#f6abb2'
    - '#871a27'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.9322863323614001
purpose: []
