analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.01450052
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#782A26'
    - '#3F1F13'
    - '#A35C40'
    - '#C13D2D'
    - '#CBAD54'
  rhythmicContrast: 0
typography_spectrum: 0.6901182
layout_spectrum: 0.1466165
cta:
  bucket: null
  version: null
  domain: null
favicon: null
name: United Colors of HIV
