name: United Colors of HIV
favicon: null
layout_spectrum: 0
typography_spectrum: 0.174687520833686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#808080'
    - '#000000'
    - '#ebe6e3'
    - '#ddb800'
    - '#00543a'
  brandStrength: 0.1875
  lightness: 0.6093438498210162
  saturation: 0.8125
  rhythmicContrast: 0.9322863323614001
purpose: []
