favicon: null
name: United Colors of HIV
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 0.5182599
  lightness: 1
  brandColors:
    - '#000000'
    - '#F7FCF6'
    - '#2B2B2B'
    - '#B1B5B0'
    - '#828282'
  rhythmicContrast: 0
typography_spectrum: 0.6901182
layout_spectrum: 1
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
