name: United Colors of HIV
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#949599'
    - '#14744f'
    - '#100e0f'
    - '#781c27'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.9322863323614001
purpose: []
